Redirected error-reporting to stderr

diff --git a/gen-correction-file b/gen-correction-file
--- a/gen-correction-file
+++ b/gen-correction-file
@@ -36,27 +36,27 @@ do
 			shift
 			;;
         *)
-            echo "unknown option: $option"
-            exit
+            echo "$0 : ERROR : unknown option: $option" >& 2
+            exit 1
 			;;
     esac
 shift
 done
 
 if [[ $tp == -1 ]] ; then
-	echo "Tp number must be specified"
+	echo "$0 : ERROR : Tp number must be specified" >& 2
 	exit 1
 fi
 if [[ $team == -1 ]] ; then
-	echo "Team number must be specified"
+	echo "$0 : ERROR : Team number must be specified" >& 2
 	exit 1
 fi
 if [[ "$correcter" == Nemo ]] ; then
-	echo "Correcter name must be specified"
+	echo "$0 : ERROR : Correcter name must be specified" >& 2
 	exit 1
 fi
 if [[ $section == -1 ]] ; then
-	echo "section number must be specified"
+	echo "$0 : ERROR : section number must be specified" >& 2
 	exit 1
 fi
 
diff --git a/get-teams b/get-teams
--- a/get-teams
+++ b/get-teams
@@ -29,7 +29,7 @@ do
 			shift
 			;;
         *)
-            echo "unknown option: $option"
+            echo "$0 : ERROR : unknown option: $option" >& 2
             exit 1
 			;;
     esac
@@ -42,7 +42,7 @@ if [[ "$team_size" == 4 ]] ; then
 elif [[ "$team_size" == 2 ]] ; then
 	team_size=e
 else
-	echo "Team size must be 2 or 4"
+	echo "$0 : ERROR : Team size must be 2 or 4" >& 2
 	exit 1
 fi
 
