Changed get-value interface and documented clone-teams

diff --git a/get-value b/get-value
--- a/get-value
+++ b/get-value
@@ -1,11 +1,44 @@
 #!/bin/bash
 
-file=$1
-var_name=$2
-var_value=""
+################################################################################
+# Script to retrieve values from a file of key=value pairs.
+# options:
+# get-value --key key-name [--file filename]
+# -k | --key to specify the key for which we want to retrieve the value
+# [-f | --file ] to specify the file where we want to look.  Defaults to
+# settings.txt
+################################################################################
+file=settings.txt
+key=""
+while [[ $# -gt 0 ]]
+do
+	option="$1"
+	optarg="$2"
+	case "$option" in
+		-f|--file)
+			file="$optarg"
+			shift
+			;;
+		-k|--key)
+			key="$optarg"
+			shift
+			;;
+		*)
+			echo "$0 : ERROR : Unknown option $option"
+			exit 1
+			;;
+	esac
+shift
+done
+
+if [[ "$key" == "" ]] ; then
+	echo "$0 : ERROR :Key must be specified"
+fi
+
+value=""
 while read -r line; do
-	if [[ $line == ${var_name}=* ]]; then
-		var_value=${line#${var_name}=}
+	if [[ $line == ${key}=* ]]; then
+		value=${line#${key}=}
 	fi
 done < $file
-echo ${var_value}
+echo ${value}
